# Canonical private-input header schemas. These are not participant data.
OEF_INPUT_SCHEMA <- list(
  "trust_lifespan_hc.csv" = list(sheet = 1, columns = c("Age", "Sex", "SiteID", "phenotype"), any_of = list()),
  "trust_lifespan_hc_stricterQC.csv" = list(sheet = 1, columns = c("Age", "Sex", "SiteID", "phenotype"), any_of = list()),
  "trust_lifespan_hc_zscores.csv" = list(sheet = 1, columns = c("Age", "Sex", "SiteID", "phenotype"), any_of = list()),
  "trust_disease_patients.csv" = list(sheet = 1, columns = c("Age", "Sex", "SiteID", "phenotype", "Diagnosis"), any_of = list()),
  "trust_vascular_risk_zscores.csv" = list(sheet = 1, columns = c("z_score", "BMI_Code", "HT_Code", "HL_Code", "DB_Code"), any_of = list()),
  "trust_tumor_phenotypes.xlsx" = list(sheet = "Sheet1", columns = c("z_score", "Age", "Sex", "HTN", "DM", "HLP", "Tumor_Grade", "Ki67con", "Ki67dis", "IDH1"), any_of = list(c("BMI", "BMI_Code"))),
  "trust_neurodegenerative_phenotypes.xlsx" = list(sheet = "Sheet1", columns = c("z_score", "APOE_Code", "HTN", "DM", "HLP", "MMSE", "MOCA", "AFT", "SDMT", "NPI"), any_of = list(c("BMI", "BMI_Code"))),
  "trust_caffeine_followup.xlsx" = list(sheet = 1, columns = c("Time", "OEF_Day1", "OEF_Day2"), any_of = list()),
  "trust_traveling_subjects.xlsx" = list(sheet = 1, columns = c("name", "OEF_SJTU", "OEF_ZJU"), any_of = list(), note = "Step27 also analyzes R2 when both R2_SJTU and R2_ZJU columns are supplied."),
  "trust_hc_blood_sensitivity.xlsx" = list(sheet = "Sheet1", columns = c("Age", "SiteID", "OEF", "OEF_RegionMatched", "OEF_Zierk", "OEF_MahlMean", "OEF_CohortEmpirical", "T2", "dR2", "OEF_Ya_LuHybrid", "OEF_Ya_CrapoHybrid"), any_of = list(c("Sex", "Sex(M0F1)"))),
  "trust_patient_blood_sensitivity.xlsx" = list(sheet = "Sheet1", columns = c("Age", "SiteID", "OEF", "OEF_RegionMatched", "OEF_Zierk", "OEF_MahlMean", "OEF_CohortEmpirical", "Diagnosis"), any_of = list(c("Sex", "Sex(M0F1)"))),
  "trust_community_aging_cbf.xlsx" = list(sheet = "Sheet1", columns = c("Age", "Sex", "OEF", "OEF zscore", "CBF", "CMRO2", "BMI_Code", "HT_Code", "HL_Code", "DB_Code"), any_of = list()),
  "trust_pediatric_osa_cbf.xlsx" = list(sheet = 1, columns = c("Age", "Diagnosis", "CBF", "CMRO2"), any_of = list(c("Sex", "Sex(M0F1)"), c("OEFz", "OEFzscore", "OEF zscore"))),
  "trust_cognitive_aging_cbf.xlsx" = list(sheet = 1, columns = c("Age", "Sex", "Diagnosis", "CBF", "OEF zscore", "MMSE", "MoCA", "BMI_Code", "HT_Code", "HL_Code", "DB_Code"), any_of = list(), note = "A raw OEF column is also required; duplicate repaired OEF headers must be selected explicitly in config.local.R.")
)
OEF_STEP_INPUTS <- list(
  "0" = c("trust_lifespan_hc.csv"),
  "1" = c("trust_lifespan_hc.csv"),
  "2" = c("trust_vascular_risk_zscores.csv"),
  "3" = c("trust_lifespan_hc_zscores.csv", "trust_disease_patients.csv"),
  "4" = c("trust_tumor_phenotypes.xlsx"),
  "5" = c("trust_neurodegenerative_phenotypes.xlsx"),
  "6" = c("trust_caffeine_followup.xlsx"),
  "7" = c("trust_traveling_subjects.xlsx"),
  "8" = c("trust_hc_blood_sensitivity.xlsx", "trust_patient_blood_sensitivity.xlsx"),
  "9" = c("trust_hc_blood_sensitivity.xlsx"),
  "10" = c("trust_hc_blood_sensitivity.xlsx", "trust_patient_blood_sensitivity.xlsx"),
  "11" = c("trust_lifespan_hc_zscores.csv", "trust_disease_patients.csv"),
  "12" = c("trust_vascular_risk_zscores.csv"),
  "13" = c("trust_community_aging_cbf.xlsx"),
  "14" = c("trust_pediatric_osa_cbf.xlsx"),
  "15" = c("trust_cognitive_aging_cbf.xlsx"),
  "16" = c("trust_hc_blood_sensitivity.xlsx"),
  "17" = c("trust_hc_blood_sensitivity.xlsx"),
  "18" = c("trust_hc_blood_sensitivity.xlsx"),
  "19" = character(),
  "20" = character(),
  "21" = c("trust_lifespan_hc.csv"),
  "22" = c("trust_lifespan_hc.csv"),
  "23" = c("trust_lifespan_hc.csv"),
  "24" = c("trust_lifespan_hc.csv"),
  "25" = c("trust_lifespan_hc_stricterQC.csv"),
  "26" = c("trust_lifespan_hc.csv"),
  "27" = c("trust_traveling_subjects.xlsx")
)
