# Paired OEF and R2 comparisons between SJTU and ZJU.
source("R/lib/oef_utils.R")
source("R/lib/traveling_comparison.R")
oef_start_step("Step27")
InputFile <- oef_input("trust_traveling_subjects.xlsx")
OutDir <- oef_output("traveling_site_comparison")
if (!file.exists(InputFile)) stop("Missing input: ", InputFile)
if (!requireNamespace("readxl", quietly = TRUE)) stop("Install readxl to read the input workbook.")
dat <- as.data.frame(readxl::read_excel(InputFile, sheet = 1))
result <- traveling_site_comparison(dat)
dir.create(OutDir, recursive = TRUE, showWarnings = FALSE)
write.csv(result$summary, file.path(OutDir, "paired_R2_OEF_site_comparison.csv"), row.names = FALSE)
write.csv(result$paired_values, file.path(OutDir, "paired_values_private.csv"), row.names = FALSE)
write.csv(result$availability, file.path(OutDir, "metric_availability.csv"), row.names = FALSE)
print(result$summary)
